### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by vrescobar** [kritzcreek/purescript-wasm#1]
Hi there,

I am interested in the project, I would like to know the current status, any readme.md, status, helloworld and building commands would be a great additon.

If that's compatible with the project.

**Comment by kritzcreek** [comment]
Hey, the status is basically "incomplete but workable". It's a PureScript library that can be used to generate Wasm code. It's _NOT_ a PureScript to Wasm compiler.

Adding a README would be a good idea, I just haven't gotten around to it.
The included `example/` directory contains a compiler for a small language that can serve as a bigger hello world.
As for building commands... I'm not sure what you're looking for there, it's a regular PureScript library, it builds like all of them. The `package.json` file has scripts that build the example compiler, which includes building the wasm library.

I'll see if I can get around to adding a README, but no promises.
